import { jsPDF } from 'jspdf';
import type { Deadline, Subject } from '@/types';
import { groupDeadlinesByDate, relativeDeadlineLabel } from '@/utils/deadlines';

export type ExportGrouping = 'category' | 'subject';

interface ExportOptions {
  studentName: string;
  semesterName: string;
  deadlines: Deadline[];
  subjects: Subject[];
  scopeLabel: string;
  grouping: ExportGrouping;
}

function formatDate(ts: number): string {
  return new Date(ts).toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function getSubjectName(deadline: Deadline, subjects: Subject[]): string {
  const s = subjects.find((s) => s.id === deadline.subjectId);
  return s ? s.name : 'Other';
}

function groupByCategory(deadlines: Deadline[]) {
  const groups = groupDeadlinesByDate(deadlines);
  return groups.map((g) => ({
    cat: g.category,
    label: g.sublabel ? `${g.label} (${g.sublabel})` : g.label,
    hex: g.hex,
    items: g.items,
  }));
}

function groupBySubject(deadlines: Deadline[], subjects: Subject[]) {
  const sorted = [...deadlines].sort((a, b) => a.dueDate - b.dueDate);
  const withSubject = subjects.filter((s) =>
    sorted.some((d) => d.subjectId === s.id),
  );
  const groups = withSubject.map((subject) => ({
    label: subject.name,
    hex: '#8a8a82',
    items: sorted.filter((d) => d.subjectId === subject.id),
  }));
  const noSubject = sorted.filter((d) => !d.subjectId);
  if (noSubject.length > 0) {
    groups.push({ label: 'Other', hex: '#8a8a82', items: noSubject });
  }
  return groups;
}

export function downloadDeadlinesAsText(opts: ExportOptions): void {
  const { studentName, semesterName, deadlines, subjects, scopeLabel, grouping } = opts;
  const sorted = [...deadlines].sort((a, b) => a.dueDate - b.dueDate);
  const groups =
    grouping === 'subject'
      ? groupBySubject(sorted, subjects)
      : groupByCategory(sorted);
  const date = new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  const lines: string[] = [];
  lines.push('='.repeat(50));
  lines.push('  DEADLINE REPORT');
  lines.push('='.repeat(50));
  lines.push('');
  lines.push(`Student:   ${studentName || '—'}`);
  lines.push(`Semester:  ${semesterName}`);
  lines.push(`Scope:     ${scopeLabel}`);
  lines.push(`Format:    ${grouping === 'subject' ? 'Subject-wise' : 'Date-wise'}`);
  lines.push(`Generated:  ${date}`);
  lines.push('');
  lines.push('-'.repeat(50));
  lines.push('');

  if (sorted.length === 0) {
    lines.push('No deadlines found.');
  } else {
    groups.forEach((g) => {
      lines.push(`[${g.label.toUpperCase()}] (${g.items.length})`);
      lines.push('');
      g.items.forEach((d, i) => {
        lines.push(`  ${i + 1}. ${d.title}`);
        lines.push(`     Due: ${formatDate(d.dueDate)}  —  ${relativeDeadlineLabel(d)}`);
        lines.push(`     Subject: ${getSubjectName(d, subjects)}`);
        if (d.description) lines.push(`     Notes: ${d.description}`);
        lines.push(`     Status: ${d.completed ? 'Completed' : 'Pending'}`);
        lines.push('');
      });
      lines.push('-'.repeat(50));
      lines.push('');
    });
  }

  lines.push('');
  lines.push('Generated by eStudesk');

  const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `deadlines-${semesterName.replace(/\s+/g, '-').toLowerCase()}-${scopeLabel.replace(/\s+/g, '-').toLowerCase()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadDeadlinesAsPDF(opts: ExportOptions): void {
  const { studentName, semesterName, deadlines, subjects, scopeLabel, grouping } = opts;
  const sorted = [...deadlines].sort((a, b) => a.dueDate - b.dueDate);
  const groups =
    grouping === 'subject'
      ? groupBySubject(sorted, subjects)
      : groupByCategory(sorted);
  const date = new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Header band — light ink-saving shade
  doc.setFillColor(238, 235, 228);
  doc.rect(0, 0, pageW, 32, 'F');
  // Thin accent line at bottom of header
  doc.setDrawColor(200, 196, 185);
  doc.setLineWidth(0.5);
  doc.line(0, 32, pageW, 32);
  doc.setTextColor(50, 50, 45);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Deadline Report', margin, 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(110, 108, 100);
  doc.text(`Generated ${date}`, margin, 22);
  doc.text('eStudesk', pageW - margin, 22, { align: 'right' });
  y = 42;

  // Info block
  doc.setTextColor(60, 60, 55);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Student', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(studentName || '—', margin + 28, y);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.text('Semester', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(semesterName, margin + 28, y);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.text('Scope', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(scopeLabel, margin + 28, y);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.text('Format', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(grouping === 'subject' ? 'Subject-wise' : 'Date-wise', margin + 28, y);
  y += 8;

  // Divider
  doc.setDrawColor(220, 218, 210);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  if (sorted.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(11);
    doc.setTextColor(140, 140, 130);
    doc.text('No deadlines found.', margin, y);
  } else {
    groups.forEach((g) => {
      // Check space for section header + at least one item
      if (y > pageH - 30) {
        doc.addPage();
        y = margin;
      }

      // Group header bar — light tinted background with dark text
      const catLabel = `${g.label}  (${g.items.length})`;
      doc.setFillColor(245, 243, 237);
      doc.roundedRect(margin, y - 4, contentW, 7, 1, 1, 'F');
      // Left accent stripe
      doc.setFillColor(g.hex);
      doc.roundedRect(margin, y - 4, 1.5, 7, 0.5, 0.5, 'F');
      doc.setTextColor(50, 50, 45);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text(catLabel.toUpperCase(), margin + 4, y + 0.5);
      y += 8;

      g.items.forEach((d) => {
        if (y > pageH - 25) {
          doc.addPage();
          y = margin;
        }

        const subjName = getSubjectName(d, subjects);
        const dueStr = formatDate(d.dueDate);
        const relStr = relativeDeadlineLabel(d);

        // Title
        doc.setTextColor(40, 40, 35);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        const titleLines = doc.splitTextToSize(d.title, contentW - 10);
        doc.text(titleLines, margin + 2, y);
        y += titleLines.length * 4.5;

        // Meta line
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(120, 120, 110);
        const metaLine = `Due: ${dueStr}   |   ${relStr}   |   Subject: ${subjName}   |   ${d.completed ? 'Completed' : 'Pending'}`;
        doc.text(metaLine, margin + 2, y);
        y += 4;

        // Description
        if (d.description) {
          const descLines = doc.splitTextToSize(d.description, contentW - 10);
          doc.setTextColor(150, 150, 140);
          doc.setFontSize(8);
          doc.text(descLines, margin + 2, y);
          y += descLines.length * 3.5;
        }

        y += 3;
        doc.setDrawColor(235, 233, 225);
        doc.setLineWidth(0.2);
        doc.line(margin + 2, y, pageW - margin - 2, y);
        y += 3;
      });
      y += 2;
    });
  }

  // Footer page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageW / 2,
      pageH - 8,
      { align: 'center' },
    );
  }

  doc.save(`deadlines-${semesterName.replace(/\s+/g, '-').toLowerCase()}-${scopeLabel.replace(/\s+/g, '-').toLowerCase()}.pdf`);
}
